packages:
  - 'core'
  - 'packages/*'

allowBuilds:
  electron: true
  esbuild: true
  electron-winstaller: true
  iconv-corefoundation: true

minimumReleaseAgeExclude:
  - "vite-plugin-electron@0.29.1"
  - "electron@41.0.2"
