import { describe, it, expect } from 'vitest'
import { buildVideoFilterGraph } from '../video-filter'
import { buildAudioPcmArgs } from '../audio-mix'
import type { ExportClip } from '../timeline'
import {
  buildKeyframeFfmpegExpression,
  sampleClipAt,
  sampleKeyframeTrack,
} from '../../../core/src/keyframes'
import type { KeyframeTrack, TimelineClip } from '../../../core/src/project-model'
import { timelineClipSchema } from '../../../core/src/project-model'

/**
 * JS evaluator for FFmpeg expression strings generated by buildKeyframeFfmpegExpression.
 * Supports: if(c, a, b), lte(a, b), lt(a, b), pow(a, b), PI, min, max, round, isnan.
 */
function evalFfmpegExpr(expr: string, t: number): number {
  const jsExpr = expr
    .replace(/\bPI\b/g, `${Math.PI}`)
    .replace(/\bisnan\(([^)]+)\)/g, 'Number.isNaN($1)')
    .replace(/\blte\(([^,]+),([^)]+)\)/g, '(($1)<=($2))')
    .replace(/\blt\(([^,]+),([^)]+)\)/g, '(($1)<($2))')
    .replace(/\bpow\(([^,]+),([^)]+)\)/g, 'Math.pow($1,$2)')
    .replace(/\bround\(/g, 'Math.round(')
    .replace(/\bmin\(/g, 'Math.min(')
    .replace(/\bmax\(/g, 'Math.max(')

  function transformIfs(s: string): string {
    const ifIdx = s.indexOf('if(')
    if (ifIdx === -1) return s

    let depth = 0
    let startParen = ifIdx + 2
    let comma1 = -1
    let comma2 = -1
    let endParen = -1

    for (let i = startParen; i < s.length; i++) {
      if (s[i] === '(') {
        depth++
      } else if (s[i] === ')') {
        depth--
        if (depth === 0) {
          endParen = i
          break
        }
      } else if (s[i] === ',' && depth === 1) {
        if (comma1 === -1) {
          comma1 = i
        } else if (comma2 === -1) {
          comma2 = i
        }
      }
    }

    if (comma1 === -1 || comma2 === -1 || endParen === -1) {
      return s
    }

    const cond = transformIfs(s.slice(startParen + 1, comma1))
    const thenPart = transformIfs(s.slice(comma1 + 1, comma2))
    const elsePart = transformIfs(s.slice(comma2 + 1, endParen))

    const replaced = `((${cond})?(${thenPart}):(${elsePart}))`
    return s.slice(0, ifIdx) + replaced + transformIfs(s.slice(endParen + 1))
  }

  const transformed = transformIfs(jsExpr)
  const fn = new Function('t', `return (${transformed});`)
  return fn(t)
}

describe('KE-204: Keyframe to FFmpeg Filtergraph Translation', () => {
  describe('Non-regression: clips without keyframes generate exact legacy filtergraph', () => {
    it('generates the exact legacy baseline filtergraph string for static visual clips', () => {
      const clip: ExportClip = {
        path: 'C:/media/test.mp4',
        type: 'video',
        startTime: 0,
        duration: 5,
        trimStart: 0,
        speed: 1,
        reversed: false,
        flipH: false,
        flipV: false,
        opacity: 80,
        trackIndex: 0,
        muted: false,
        volume: 1,
        transform: {
          scale: 120,
          positionX: 15,
          positionY: -10,
          rotation: 45,
          cropTop: 0,
          cropRight: 0,
          cropBottom: 0,
          cropLeft: 0,
        },
      }

      const { filterScript } = buildVideoFilterGraph([clip], {
        width: 1920,
        height: 1080,
        fps: 30,
        totalDuration: 5,
      })

      // Must have exact legacy static tokens:
      expect(filterScript).toContain('scale=2304:1296:force_original_aspect_ratio=decrease,setsar=1')
      const rad = ((45 * Math.PI) / 180).toFixed(6)
      expect(filterScript).toContain(`rotate=${rad}:c=none:ow=rotw(${rad}):oh=roth(${rad})`)
      expect(filterScript).toContain('colorchannelmixer=aa=0.8000')
      expect(filterScript).toContain(
        'overlay=x=(main_w-overlay_w)/2+(main_w*0.150000):y=(main_h-overlay_h)/2+(main_h*-0.100000):format=auto:eof_action=pass:repeatlast=0',
      )
      expect(filterScript).not.toContain(':eval=frame')
      expect(filterScript).not.toContain('overlay=x=\'')
    })

    it('generates exact legacy audio PCM args when no volume keyframes are present', () => {
      const args1 = buildAudioPcmArgs('C:/media/audio.mp3', 2, 8, 1, false, 2)
      const args2 = buildAudioPcmArgs('C:/media/audio.mp3', 2, 8, 1, false, 2, undefined)
      expect(args1.args).toEqual(args2.args)
      expect(args1.args.join(' ')).not.toContain('volume=eval=frame')
    })
  })

  describe('Parity test: sampleClipAt vs FFmpeg filtergraph expression (< 1% diff)', () => {
    it('matches linear interpolation across multiple points within < 1%', () => {
      const track: KeyframeTrack = {
        property: 'transform.scale',
        points: [
          { t: 0, value: 100, easing: 'linear' },
          { t: 2, value: 200, easing: 'linear' },
          { t: 4, value: 50, easing: 'linear' },
        ],
      }

      const expr = buildKeyframeFfmpegExpression(track, 100, 't')

      for (let t = 0; t <= 5; t += 0.25) {
        const expected = sampleKeyframeTrack(track, t, 100)
        const actual = evalFfmpegExpr(expr, t)
        const diffPercent = Math.abs((actual - expected) / (expected || 1)) * 100
        expect(diffPercent).toBeLessThan(1)
      }
    })

    it('matches ease-in interpolation within < 1%', () => {
      const track: KeyframeTrack = {
        property: 'opacity',
        points: [
          { t: 1, value: 0, easing: 'ease-in' },
          { t: 3, value: 100, easing: 'linear' },
        ],
      }

      const expr = buildKeyframeFfmpegExpression(track, 100, 't')

      for (let t = 0; t <= 4; t += 0.2) {
        const expected = sampleKeyframeTrack(track, t, 100)
        const actual = evalFfmpegExpr(expr, t)
        const diffPercent = Math.abs(actual - expected)
        expect(diffPercent).toBeLessThan(1)
      }
    })

    it('matches ease-out interpolation within < 1%', () => {
      const track: KeyframeTrack = {
        property: 'transform.positionX',
        points: [
          { t: 0, value: -50, easing: 'ease-out' },
          { t: 2, value: 50, easing: 'linear' },
        ],
      }

      const expr = buildKeyframeFfmpegExpression(track, 0, 't')

      for (let t = 0; t <= 3; t += 0.2) {
        const expected = sampleKeyframeTrack(track, t, 0)
        const actual = evalFfmpegExpr(expr, t)
        const diffPercent = Math.abs(actual - expected)
        expect(diffPercent).toBeLessThan(1)
      }
    })

    it('matches ease-in-out interpolation within < 1%', () => {
      const track: KeyframeTrack = {
        property: 'transform.rotation',
        points: [
          { t: 0.5, value: 0, easing: 'ease-in-out' },
          { t: 2.5, value: 360, easing: 'linear' },
        ],
      }

      const expr = buildKeyframeFfmpegExpression(track, 0, 't')

      for (let t = 0; t <= 3; t += 0.25) {
        const expected = sampleKeyframeTrack(track, t, 0)
        const actual = evalFfmpegExpr(expr, t)
        const diffPercent = Math.abs(actual - expected)
        expect(diffPercent).toBeLessThan(1)
      }
    })

    it('matches hold easing exactly', () => {
      const track: KeyframeTrack = {
        property: 'transform.scale',
        points: [
          { t: 0, value: 100, easing: 'hold' },
          { t: 1.5, value: 200, easing: 'linear' },
        ],
      }

      const expr = buildKeyframeFfmpegExpression(track, 100, 't')

      for (let t = 0; t <= 3; t += 0.25) {
        const expected = sampleKeyframeTrack(track, t, 100)
        const actual = evalFfmpegExpr(expr, t)
        expect(actual).toBeCloseTo(expected, 4)
      }
    })

    it('matches full clip animatable properties sampled via sampleClipAt', () => {
      const timelineClip: TimelineClip = timelineClipSchema.parse({
        id: 'clip_k1',
        assetId: null,
        type: 'video',
        startTime: 1,
        duration: 4,
        trimStart: 0,
        trimEnd: 0,
        speed: 1,
        reversed: false,
        muted: false,
        volume: 1,
        trackIndex: 0,
        asset: null,
        opacity: 100,
        transform: {
          scale: 100,
          positionX: 0,
          positionY: 0,
          rotation: 0,
          cropTop: 0,
          cropRight: 0,
          cropBottom: 0,
          cropLeft: 0,
        },
        keyframes: [
          {
            property: 'transform.scale',
            points: [
              { t: 0, value: 100, easing: 'linear' },
              { t: 2, value: 150, easing: 'ease-in-out' },
              { t: 4, value: 80, easing: 'linear' },
            ],
          },
          {
            property: 'transform.positionX',
            points: [
              { t: 0, value: -20, easing: 'ease-out' },
              { t: 4, value: 20, easing: 'linear' },
            ],
          },
          {
            property: 'transform.rotation',
            points: [
              { t: 1, value: 0, easing: 'ease-in' },
              { t: 3, value: 90, easing: 'linear' },
            ],
          },
          {
            property: 'opacity',
            points: [
              { t: 0, value: 0, easing: 'linear' },
              { t: 1, value: 100, easing: 'hold' },
              { t: 3, value: 50, easing: 'linear' },
            ],
          },
          {
            property: 'volume',
            points: [
              { t: 0, value: 0.2, easing: 'linear' },
              { t: 2, value: 1.5, easing: 'ease-in-out' },
              { t: 4, value: 0.8, easing: 'linear' },
            ],
          },
        ],
      })

      const scaleExpr = buildKeyframeFfmpegExpression(
        timelineClip.keyframes?.find(k => k.property === 'transform.scale'),
        100,
        't',
      )
      const posXExpr = buildKeyframeFfmpegExpression(
        timelineClip.keyframes?.find(k => k.property === 'transform.positionX'),
        0,
        't',
      )
      const rotExpr = buildKeyframeFfmpegExpression(
        timelineClip.keyframes?.find(k => k.property === 'transform.rotation'),
        0,
        't',
      )
      const opExpr = buildKeyframeFfmpegExpression(
        timelineClip.keyframes?.find(k => k.property === 'opacity'),
        100,
        't',
      )
      const volExpr = buildKeyframeFfmpegExpression(
        timelineClip.keyframes?.find(k => k.property === 'volume'),
        1,
        't',
      )

      for (let t = 0; t <= timelineClip.duration; t += 0.5) {
        const sampled = sampleClipAt(timelineClip, t)

        const evalScale = evalFfmpegExpr(scaleExpr, t)
        expect(Math.abs((evalScale - sampled.scale) / (sampled.scale || 1)) * 100).toBeLessThan(1)

        const evalPosX = evalFfmpegExpr(posXExpr, t)
        expect(Math.abs(evalPosX - sampled.positionX)).toBeLessThan(1)

        const evalRot = evalFfmpegExpr(rotExpr, t)
        expect(Math.abs(evalRot - sampled.rotation)).toBeLessThan(1)

        const evalOp = evalFfmpegExpr(opExpr, t)
        expect(Math.abs(evalOp - sampled.opacity)).toBeLessThan(1)

        const evalVol = evalFfmpegExpr(volExpr, t)
        expect(Math.abs((evalVol - sampled.volume) / (sampled.volume || 1)) * 100).toBeLessThan(1)
      }
    })
  })

  describe('Filtergraph output for keyframed clips', () => {
    it('produces eval=frame scale expression when scale keyframes exist', () => {
      const clip: ExportClip = {
        path: 'C:/media/video.mp4',
        type: 'video',
        startTime: 0,
        duration: 5,
        trimStart: 0,
        speed: 1,
        reversed: false,
        flipH: false,
        flipV: false,
        opacity: 100,
        trackIndex: 0,
        muted: false,
        volume: 1,
        keyframes: [
          {
            property: 'transform.scale',
            points: [
              { t: 0, value: 100, easing: 'linear' },
              { t: 2, value: 150, easing: 'linear' },
            ],
          },
        ],
      }

      const { filterScript } = buildVideoFilterGraph([clip], {
        width: 1920,
        height: 1080,
        fps: 30,
        totalDuration: 5,
      })

      expect(filterScript).toContain("scale=w='max(2,round(1920*max(0.01,(")
      expect(filterScript).toContain(':eval=frame,setsar=1')
    })

    it('produces rotate hypot bounding box and expression when rotation keyframes exist', () => {
      const clip: ExportClip = {
        path: 'C:/media/video.mp4',
        type: 'video',
        startTime: 0,
        duration: 5,
        trimStart: 0,
        speed: 1,
        reversed: false,
        flipH: false,
        flipV: false,
        opacity: 100,
        trackIndex: 0,
        muted: false,
        volume: 1,
        keyframes: [
          {
            property: 'transform.rotation',
            points: [
              { t: 0, value: 0, easing: 'linear' },
              { t: 2, value: 180, easing: 'linear' },
            ],
          },
        ],
      }

      const { filterScript } = buildVideoFilterGraph([clip], {
        width: 1920,
        height: 1080,
        fps: 30,
        totalDuration: 5,
      })

      expect(filterScript).toContain("rotate=a='((")
      expect(filterScript).toContain("*PI/180)'")
      expect(filterScript).toContain(":ow='hypot(in_w,in_h)':oh='hypot(in_w,in_h)'")
    })

    it('produces colorchannelmixer dynamic aa expression when opacity keyframes exist', () => {
      const clip: ExportClip = {
        path: 'C:/media/video.mp4',
        type: 'video',
        startTime: 0,
        duration: 5,
        trimStart: 0,
        speed: 1,
        reversed: false,
        flipH: false,
        flipV: false,
        opacity: 100,
        trackIndex: 0,
        muted: false,
        volume: 1,
        keyframes: [
          {
            property: 'opacity',
            points: [
              { t: 0, value: 100, easing: 'linear' },
              { t: 2, value: 0, easing: 'linear' },
            ],
          },
        ],
      }

      const { filterScript } = buildVideoFilterGraph([clip], {
        width: 1920,
        height: 1080,
        fps: 30,
        totalDuration: 5,
      })

      expect(filterScript).toContain("colorchannelmixer=aa='max(0,min(1,(")
    })

    it('produces overlay with eval=frame and relative clip time when position keyframes exist', () => {
      const clip: ExportClip = {
        path: 'C:/media/video.mp4',
        type: 'video',
        startTime: 2,
        duration: 4,
        trimStart: 0,
        speed: 1,
        reversed: false,
        flipH: false,
        flipV: false,
        opacity: 100,
        trackIndex: 0,
        muted: false,
        volume: 1,
        keyframes: [
          {
            property: 'transform.positionX',
            points: [
              { t: 0, value: -50, easing: 'linear' },
              { t: 4, value: 50, easing: 'linear' },
            ],
          },
        ],
      }

      const { filterScript } = buildVideoFilterGraph([clip], {
        width: 1920,
        height: 1080,
        fps: 30,
        totalDuration: 6,
      })

      expect(filterScript).toContain(':eval=frame:format=auto:eof_action=pass')
      expect(filterScript).toContain('(t-2.000000)')
    })

    it('produces volume=eval=frame filter argument in buildAudioPcmArgs when volume keyframes exist', () => {
      const volTrack: KeyframeTrack = {
        property: 'volume',
        points: [
          { t: 0, value: 0, easing: 'linear' },
          { t: 2, value: 1.5, easing: 'linear' },
        ],
      }

      const { args } = buildAudioPcmArgs('C:/media/audio.mp3', 0, 5, 1, false, 2, volTrack)
      const afArg = args[args.indexOf('-af') + 1]

      expect(afArg).toContain("volume=eval=frame:volume='if(isnan(t),1.0,(")
    })
  })
})
