export type StickerCategory = 'emoji' | 'badge' | 'arrow' | 'icon'

export interface StickerDefinition {
  id: string
  name: string
  category: StickerCategory
  filename: string
  keywords: string[]
  isAnimated?: boolean
  width?: number
  height?: number
}

export const STICKER_DEFINITIONS: StickerDefinition[] = [
  {
    id: 'star',
    name: 'Ngôi sao vàng',
    category: 'badge',
    filename: 'star.png',
    keywords: ['star', 'sao', 'rating', 'favorite', 'gold'],
    width: 512,
    height: 512,
  },
  {
    id: 'heart',
    name: 'Trái tim yêu',
    category: 'emoji',
    filename: 'heart.png',
    keywords: ['heart', 'love', 'tim', 'thích', 'red'],
    width: 512,
    height: 512,
  },
  {
    id: 'fire',
    name: 'Ngọn lửa hot',
    category: 'emoji',
    filename: 'fire.png',
    keywords: ['fire', 'hot', 'lửa', 'cháy', 'trending', 'flame'],
    width: 512,
    height: 512,
  },
  {
    id: 'sparkles',
    name: 'Lấp lánh thần kỳ',
    category: 'badge',
    filename: 'sparkles.png',
    keywords: ['sparkles', 'magic', 'shine', 'lấp lánh', 'glow'],
    width: 512,
    height: 512,
  },
  {
    id: 'thumbs-up',
    name: 'Thích (Like)',
    category: 'emoji',
    filename: 'thumbs-up.png',
    keywords: ['like', 'thumbs up', 'thích', 'tuyệt', 'agree'],
    width: 512,
    height: 512,
  },
  {
    id: 'check-badge',
    name: 'Tích xanh xác minh',
    category: 'badge',
    filename: 'check-badge.png',
    keywords: ['check', 'verified', 'xác minh', 'tick', 'blue'],
    width: 512,
    height: 512,
  },
  {
    id: 'party-popper',
    name: 'Pháo hoa chúc mừng',
    category: 'badge',
    filename: 'party-popper.png',
    keywords: ['party', 'celebrate', 'pháo', 'chúc mừng', 'confetti'],
    width: 512,
    height: 512,
  },
  {
    id: 'warning',
    name: 'Biển báo cảnh báo',
    category: 'icon',
    filename: 'warning.png',
    keywords: ['warning', 'alert', 'cảnh báo', 'chú ý', 'danger'],
    width: 512,
    height: 512,
  },
  {
    id: 'smile',
    name: 'Mặt cười tươi',
    category: 'emoji',
    filename: 'smile.png',
    keywords: ['smile', 'happy', 'cười', 'vui', 'cute'],
    width: 512,
    height: 512,
  },
  {
    id: 'cool-sunglasses',
    name: 'Mặt ngầu đeo kính',
    category: 'emoji',
    filename: 'cool-sunglasses.png',
    keywords: ['cool', 'sunglasses', 'ngầu', 'kính râm'],
    width: 512,
    height: 512,
  },
  {
    id: 'laugh-tears',
    name: 'Cười ra nước mắt',
    category: 'emoji',
    filename: 'laugh-tears.png',
    keywords: ['laugh', 'lol', 'hài hước', 'cười vỡ bụng', 'tears'],
    width: 512,
    height: 512,
  },
  {
    id: 'arrow-neon',
    name: 'Mũi tên Neon',
    category: 'arrow',
    filename: 'arrow-neon.png',
    keywords: ['arrow', 'pointer', 'mũi tên', 'chỉ hướng', 'neon'],
    width: 512,
    height: 512,
  },
  {
    id: 'badge-sale',
    name: 'Huy hiệu Giảm giá (SALE)',
    category: 'badge',
    filename: 'badge-sale.png',
    keywords: ['sale', 'discount', 'giảm giá', 'khuyến mãi', 'red'],
    width: 512,
    height: 512,
  },
  {
    id: 'badge-new',
    name: 'Huy hiệu Mới (NEW)',
    category: 'badge',
    filename: 'badge-new.png',
    keywords: ['new', 'mới', 'badge', 'hot', 'blue'],
    width: 512,
    height: 512,
  },
  {
    id: 'trophy',
    name: 'Cúp vàng vinh quang',
    category: 'icon',
    filename: 'trophy.png',
    keywords: ['trophy', 'winner', 'cúp', 'vô địch', 'champion'],
    width: 512,
    height: 512,
  },
  {
    id: 'lightning',
    name: 'Tia sét năng lượng',
    category: 'icon',
    filename: 'lightning.png',
    keywords: ['lightning', 'bolt', 'sét', 'nhanh', 'power'],
    width: 512,
    height: 512,
  },
  // ── Animated Stickers (Google Noto Emoji - Apache 2.0) ──
  {
    id: 'anim-laugh-tears',
    name: 'Cười ra nước mắt',
    category: 'emoji',
    filename: 'anim-laugh-tears.gif',
    keywords: ['laugh', 'lol', 'cười', 'hài hước', 'vui', 'tears', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-rofl',
    name: 'Cười lăn lộn',
    category: 'emoji',
    filename: 'anim-rofl.gif',
    keywords: ['rofl', 'laugh', 'cười', 'lăn lộn', 'haha', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-heart-eyes',
    name: 'Mắt trái tim',
    category: 'emoji',
    filename: 'anim-heart-eyes.gif',
    keywords: ['heart', 'love', 'mắt tim', 'yêu', 'mê', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-smiling-hearts',
    name: 'Nụ cười hạnh phúc',
    category: 'emoji',
    filename: 'anim-smiling-hearts.gif',
    keywords: ['smile', 'hearts', 'hạnh phúc', 'ngọt ngào', 'love', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-cool-sunglasses',
    name: 'Mặt ngầu kính râm',
    category: 'emoji',
    filename: 'anim-cool-sunglasses.gif',
    keywords: ['cool', 'sunglasses', 'ngầu', 'kính râm', 'bảnh', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-partying-face',
    name: 'Mặt tiệc tùng ăn mừng',
    category: 'emoji',
    filename: 'anim-partying-face.gif',
    keywords: ['party', 'celebrate', 'tiệc', 'ăn mừng', 'vui vẻ', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-thinking',
    name: 'Đăm chiêu suy nghĩ',
    category: 'emoji',
    filename: 'anim-thinking.gif',
    keywords: ['thinking', 'suy nghĩ', 'ngẫm', 'hỏi', 'tư duy', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-exploding-head',
    name: 'Nổ tung não (Mind blown)',
    category: 'emoji',
    filename: 'anim-exploding-head.gif',
    keywords: ['mind blown', 'shock', 'nổ não', 'bất ngờ', 'sốc', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-crying',
    name: 'Khóc nức nở',
    category: 'emoji',
    filename: 'anim-crying.gif',
    keywords: ['cry', 'sad', 'khóc', 'buồn', 'nước mắt', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-screaming',
    name: 'Hét hoảng hốt',
    category: 'emoji',
    filename: 'anim-screaming.gif',
    keywords: ['scream', 'fear', 'hét', 'sợ', 'kinh ngạc', 'hoảng', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-eyes',
    name: 'Đôi mắt liếc',
    category: 'emoji',
    filename: 'anim-eyes.gif',
    keywords: ['eyes', 'look', 'mắt', 'liếc', 'nhìn', 'hóng', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-thumbs-up',
    name: 'Thích (Like)',
    category: 'emoji',
    filename: 'anim-thumbs-up.gif',
    keywords: ['like', 'thumbs up', 'thích', 'tuyệt', 'đồng ý', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-thumbs-down',
    name: 'Không thích (Dislike)',
    category: 'emoji',
    filename: 'anim-thumbs-down.gif',
    keywords: ['dislike', 'không thích', 'chê', 'tệ', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-clapping',
    name: 'Vỗ tay tán thưởng',
    category: 'emoji',
    filename: 'anim-clapping.gif',
    keywords: ['clap', 'applause', 'vỗ tay', 'khen', 'tuyệt vời', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-raised-hands',
    name: 'Hoan hô hai tay',
    category: 'emoji',
    filename: 'anim-raised-hands.gif',
    keywords: ['celebrate', 'hoan hô', 'ăn mừng', 'yay', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-folded-hands',
    name: 'Cảm ơn / Chắp tay',
    category: 'emoji',
    filename: 'anim-folded-hands.gif',
    keywords: ['thank you', 'pray', 'cảm ơn', 'chắp tay', 'biết ơn', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-red-heart',
    name: 'Trái tim đỏ rung đập',
    category: 'emoji',
    filename: 'anim-red-heart.gif',
    keywords: ['heart', 'love', 'tim', 'yêu', 'đỏ', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-sparkling-heart',
    name: 'Trái tim lấp lánh',
    category: 'emoji',
    filename: 'anim-sparkling-heart.gif',
    keywords: ['sparkling heart', 'tim lấp lánh', 'yêu thích', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-broken-heart',
    name: 'Trái tim tan vỡ',
    category: 'emoji',
    filename: 'anim-broken-heart.gif',
    keywords: ['broken heart', 'tan vỡ', 'chia tay', 'đau lòng', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-fire',
    name: 'Ngọn lửa hot cháy',
    category: 'badge',
    filename: 'anim-fire.gif',
    keywords: ['fire', 'hot', 'cháy', 'lửa', 'trending', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-sparkles',
    name: 'Ánh sáng lấp lánh',
    category: 'badge',
    filename: 'anim-sparkles.gif',
    keywords: ['sparkles', 'magic', 'lấp lánh', 'sáng', 'thần kỳ', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-glowing-star',
    name: 'Ngôi sao tỏa sáng',
    category: 'badge',
    filename: 'anim-glowing-star.gif',
    keywords: ['star', 'glowing', 'sao', 'tỏa sáng', 'ngôi sao', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-lightning',
    name: 'Tia sét năng lượng',
    category: 'icon',
    filename: 'anim-lightning.gif',
    keywords: ['lightning', 'bolt', 'sét', 'năng lượng', 'nhanh', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-collision',
    name: 'Vụ nổ va chạm (Boom)',
    category: 'badge',
    filename: 'anim-collision.gif',
    keywords: ['boom', 'collision', 'nổ', 'va chạm', 'vfx', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-bomb',
    name: 'Bom đếm ngược nổ',
    category: 'icon',
    filename: 'anim-bomb.gif',
    keywords: ['bomb', 'bom', 'nổ', 'nguy hiểm', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-party-popper',
    name: 'Pháo hoa giấy chúc mừng',
    category: 'badge',
    filename: 'anim-party-popper.gif',
    keywords: ['party', 'confetti', 'pháo hoa', 'chúc mừng', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-bell',
    name: 'Chuông thông báo',
    category: 'icon',
    filename: 'anim-bell.gif',
    keywords: ['bell', 'subscribe', 'chuông', 'thông báo', 'nhắc nhở', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-megaphone',
    name: 'Loa phóng thanh / CTA',
    category: 'icon',
    filename: 'anim-megaphone.gif',
    keywords: ['megaphone', 'loa', 'thông báo', 'cta', 'kêu gọi', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-speech-balloon',
    name: 'Bong bóng chat',
    category: 'icon',
    filename: 'anim-speech-balloon.gif',
    keywords: ['chat', 'comment', 'bình luận', 'tin nhắn', 'nói', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-rocket',
    name: 'Tên lửa bay vút',
    category: 'icon',
    filename: 'anim-rocket.gif',
    keywords: ['rocket', 'tên lửa', 'bay', 'tăng trưởng', 'launch', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-target',
    name: 'Hồng tâm trúng đích',
    category: 'icon',
    filename: 'anim-target.gif',
    keywords: ['target', 'bullseye', 'mục tiêu', 'trúng đích', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-hundred',
    name: 'Điểm 100 tuyệt đối',
    category: 'badge',
    filename: 'anim-hundred.gif',
    keywords: ['100', 'hundred', 'hoàn hảo', 'tuyệt đối', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-crown',
    name: 'Vương miện hoàng gia',
    category: 'badge',
    filename: 'anim-crown.gif',
    keywords: ['crown', 'vương miện', 'vua', 'hoàng gia', 'top 1', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-trophy',
    name: 'Cúp vàng vô địch',
    category: 'icon',
    filename: 'anim-trophy.gif',
    keywords: ['trophy', 'cúp', 'chiến thắng', 'vô địch', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-medal-1st',
    name: 'Huy chương vàng số 1',
    category: 'badge',
    filename: 'anim-medal-1st.gif',
    keywords: ['medal', 'huy chương', 'vàng', 'nhất', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-diamond',
    name: 'Kim cương quý giá',
    category: 'badge',
    filename: 'anim-diamond.gif',
    keywords: ['diamond', 'kim cương', 'quý giá', 'vip', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-money-wings',
    name: 'Tiền bay',
    category: 'icon',
    filename: 'anim-money-wings.gif',
    keywords: ['money', 'tiền', 'đô la', 'thu nhập', 'lợi nhuận', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-check-mark',
    name: 'Tích xanh hoàn thành',
    category: 'badge',
    filename: 'anim-check-mark.gif',
    keywords: ['check', 'done', 'tích xanh', 'hoàn thành', 'xong', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
  {
    id: 'anim-warning',
    name: 'Biển báo nguy hiểm',
    category: 'icon',
    filename: 'anim-warning.gif',
    keywords: ['warning', 'cảnh báo', 'chú ý', 'nguy hiểm', 'động', 'anim'],
    isAnimated: true,
    width: 512,
    height: 512,
  },
]

export const STICKER_CATEGORIES: { id: StickerCategory | 'all' | 'custom' | 'animated'; label: string }[] = [
  { id: 'all', label: 'Tất cả' },
  { id: 'animated', label: 'Ảnh động' },
  { id: 'emoji', label: 'Emoji' },
  { id: 'badge', label: 'Huy hiệu' },
  { id: 'arrow', label: 'Mũi tên' },
  { id: 'icon', label: 'Biểu tượng' },
  { id: 'custom', label: 'Đã nhập' },
]

export const DEFAULT_STICKER_DURATION = 1.0
/** Fallback when the timeline size is unknown; see DEFAULT_STICKER_PIXELS. */
export const DEFAULT_STICKER_SCALE = 120

/**
 * How big a freshly added sticker should be, in pixels of the project frame.
 *
 * `transform.scale` is a percentage of the frame rather than a pixel size, so
 * a fixed percentage would come out tiny on a 4K timeline and huge on a 720p
 * one. Callers turn this into a percentage against the frame's short edge — a
 * square sticker is fitted to that edge before the scale is applied.
 */
export const DEFAULT_STICKER_PIXELS = 150

export function getStickerDefinition(id: string): StickerDefinition | undefined {
  return STICKER_DEFINITIONS.find(s => s.id === id)
}

export function isValidStickerId(id: string): boolean {
  return STICKER_DEFINITIONS.some(s => s.id === id)
}

export function isAnimatedSticker(filenameOrId: string): boolean {
  const def = getStickerDefinition(filenameOrId)
  if (def?.isAnimated) return true
  const lower = filenameOrId.toLowerCase()
  return lower.endsWith('.gif') || lower.endsWith('.webp')
}

export function resolveStickerRelativePath(filenameOrId: string): string {
  const def = getStickerDefinition(filenameOrId)
  const filename = def
    ? def.filename
    : (filenameOrId.endsWith('.png') || filenameOrId.endsWith('.webp') || filenameOrId.endsWith('.gif')
        ? filenameOrId
        : `${filenameOrId}.png`)
  return `stickers/${filename}`
}
